package org.hibernate.demo.jakartadata;

import org.hibernate.StatelessSession;
import org.hibernate.annotations.processing.Pattern;

import jakarta.data.repository.Delete;
import jakarta.data.repository.Find;
import jakarta.data.repository.Insert;
import jakarta.data.repository.Query;
import jakarta.data.repository.Repository;
import jakarta.data.repository.Save;
import jakarta.data.repository.Update;
import java.util.List;

/*
 Hibernate Data Repositories is backed by a StatelessSession

 It's an interface annotated with @Repository and in Hibernate the implementation is generated by an annotation processor
 */
@Repository
public interface Grocery {

	// resource accessor method (at the moment is the only one supported)
	StatelessSession session();

	// automatic query methods
	/*
	 If there is no Fruit with the given id in the database, the method throws EmptyResultException.
		There’s two ways around this if that’s not what we want:
		- declare the method to return Optional, or
		- annotate the method @jakarta.annotation.Nullable
	 */
	@Find
	Fruit fruit(Integer id);

	@Find
	/* Arguments to a parameter of an automatic query method must match exactly with the field of an entity.
	 Hibernate provides the @Pattern annotation to allow matching using like.
	 */
	Fruit fruitByName(@Pattern String name);

	//no need for separate repos
	@Find
	Vegetable vegetable(Integer id);

	// lifecycle methods, can accept also a list or array of entities e.g. addFruit(Fruit... fruit)
	@Insert
	void addFruit(Fruit fruit);

	@Insert
	void addVegetable(Vegetable vegetable);

	@Update
	void updateFruit(Fruit fruit);

	@Delete
	void deleteFruit(Fruit fruit);

	@Save // maps to upsert()
	void saveFruit(Fruit fruit);

	// annotated query methods
	/*
	An annotated query method is declared using:
		- @Query from Jakarta Data, or
		- @HQL or @SQL from org.hibernate.annotations.processing.
	 */

	@Query("where name like :pattern order by id")
	List<Vegetable> vegetableByname(String pattern);

	// default methods
	default void refresh(Fruit fruit) {
		session().upsert(fruit);
	}

}
