# Database configuration
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true
#quarkus.hibernate-orm.log.bind-parameters=true

# Ollama configuration for LangChain4j
quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.chat-model.model-id=qwen3-coder
quarkus.langchain4j.ollama.chat-model.temperature=0.0
quarkus.langchain4j.ollama.timeout=90s

# debug options
quarkus.langchain4j.ollama.log-requests=true
quarkus.langchain4j.ollama.log-responses=true
quarkus.log.level=INFO
quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.orm.jdbc.bind".level=TRACE
quarkus.log.category."org.hibernate.orm.jdbc.bind".min-level=TRACE
quarkus.log.category."org.hibernate.orm.jdbc.extract".level=TRACE
quarkus.log.category."org.hibernate.orm.jdbc.extract".min-level=TRACE
# quarkus.package.jar.type=uber-jar