package org.hibernate.demo.assistant;

import org.hibernate.Session;
import org.hibernate.SharedSessionContract;
import org.hibernate.query.SelectionQuery;
import org.hibernate.tool.language.internal.MetamodelJsonSerializerImpl;

import io.quarkiverse.mcp.server.Tool;
import io.quarkiverse.mcp.server.ToolArg;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;
import java.io.IOException;

/**
 * Hibernate Assistant MCP Server implementation.
 */
@Singleton
public class HibernateAssistantMCP {
	@Inject
	Session session;

	@Inject
	HibernateAssistantLC4J assistant;

	@Tool(name = "hibernate_get_metamodel", description = "Retrieve a textual (JSON) representation of the Hibernate Metamodel, i.e. the entities, " +
			"properties and relationships defined in the persistence layer, that can be used to access the database.")
	public String getMetamodel() {
		return MetamodelJsonSerializerImpl.INSTANCE.toString( session.getSessionFactory().getMetamodel() );
	}

	@Tool(name = "hibernate_query", description = "Execute a query against the database using the Hibernate Assistant. " +
			"Pass a natural language message and get a natural language response based on the results of the query.")
	public String executeQuery(@ToolArg(description = "Natural language query to execute") String query) {
		return assistant.executeQuery( query, session );
	}

	/**
	 * Creates a {@link SelectionQuery} by providing the specified natural language {@code message} to the LLM
	 * (see {@link org.hibernate.tool.language.HibernateAssistant#createAiQuery(String, SharedSessionContract)}) and executes it, returning a
	 * JSON representation of the resulting data.
	 *
	 * @param message the natural language prompt
	 *
	 * @return the {@link SelectionQuery} generated by the LLM
	 */
	@Tool(name = "hibernate_query_json", description = "Execute a query against the database using the Hibernate Assistant. " +
			"Pass a natural language message and get a JSON representation of the resulting data.")
	public String executeQueryToJson(@ToolArg(description = "Natural language query to execute") String message)
			throws IOException {
		final SelectionQuery<?> query = assistant.createAiQuery( message, session );
		return assistant.executeQueryToJson( query, session );
	}
}
